vscode:
  extensions:
    - blockstack.clarity@0.0.5:rBhb1NsIYs1/wpFyiyXNdA==
    - lgalabru.clarity-lsp@0.2.66:PEBgheot/B02RfVLfwbzYg==
    - CoenraadS.bracket-pair-colorizer-2@0.2.0:R8flOpw1fEZe6KyMNNNqBQ==