tasks:
  - init: npm i --global npx && npm i --global @stacks/cli

vscode:
  extensions:
    - blockstack.clarity@0.0.5:rBhb1NsIYs1/wpFyiyXNdA==
    - lgalabru.clarity-lsp@0.2.66:PEBgheot/B02RfVLfwbzYg==
    - CoenraadS.bracket-pair-colorizer@1.0.61:+jQByqALW0iXkhpd2yzYzQ==
